name: Lint
 
on:
  pull_request:
  push:
 
env:
  NODE_VERSION: 16
 
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
 
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # Install dependencies
 
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint
