name: Lint
 
on:
  push:
 
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.9.1'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - name: Build
        run: yarn install
      - name: Build
        run: yarn lint
